// generated by scripts/embed-migrations.ts — run `pnpm db:generate`, do not edit
export const migrations: { id: string; statements: string[] }[] = [
  {
    "id": "0000_tough_matthew_murdock",
    "statements": [
      "CREATE TABLE `app_state` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);",
      "CREATE TABLE `instances` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`pid` integer NOT NULL,\n\t`tty` text,\n\t`socket` text NOT NULL,\n\t`cdp_port` integer,\n\t`url` text DEFAULT '' NOT NULL,\n\t`title` text DEFAULT '' NOT NULL,\n\t`favicon` text,\n\t`loading` integer DEFAULT false NOT NULL,\n\t`can_go_back` integer DEFAULT false NOT NULL,\n\t`can_go_forward` integer DEFAULT false NOT NULL,\n\t`find_matches` text,\n\t`zoom` real DEFAULT 1 NOT NULL,\n\t`tabs` text,\n\t`viewport` text,\n\t`started_at` integer NOT NULL\n);"
    ]
  },
  {
    "id": "0001_medical_molecule_man",
    "statements": [
      "CREATE TABLE `settings` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`devtools_dock` text DEFAULT 'bottom' NOT NULL,\n\t`devtools_fraction` real DEFAULT 0.4 NOT NULL\n);"
    ]
  },
  {
    "id": "0002_fat_marten_broadcloak",
    "statements": [
      "ALTER TABLE `instances` ADD `split_dir` text;",
      "ALTER TABLE `instances` ADD `parent_tty` text;"
    ]
  }
];
